name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
             
    - name: Build the Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: vikasdfghjl/weatherapp-dot-py
        registry: docker.io
        dockerfile: Docker/Dockerfile
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
