name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
    
    - name: set up docker
      uses: docker/setup-qemu-action@v3
    
    - name: login to dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Build the Docker image
      run: |
        docker build -t weatherapp-dot-py:latest -f Docker/Dockerfile .
    
    - name: tagging the docker image
      run: |
        docker tag weatherapp-dot-py:latest vikasdfghjl/weatherapp-dot-py:${{ steps.docker_meta.outputs.labels }}
    
    - name: push the image
      run: |
        docker push vikasdfghjl/weatherapp-dot-py:${{ steps.docker_meta.outputs.labels }}
        
