name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
    
    - name: set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: set up Docker BuildX
      uses: docker/setup-buildx-action@v3
    
    - name: login to dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Build and Push the Docker image
      uses: docker/build-push-action@v5
      with:
        context: Docker/Dockerfile
        push: true
        tags: vikasdfghjl/weatherapp-dot-py:${{ github.run_number }}        
